### ISSUE TITLE
instru.nenufar_ant_gain() limited to 80 MHz

### ISSUE THREAD

**Issue by flomertens** [AlanLoh/nenupy#22]
It could be nice to have it up 85 MHz, or at least a very raw estimates, so that ABeam et al. can work to frequencies >= 80 MHz.

**Comment by AlanLoh** [comment]
Found a solution:

* Gather HEALPIx antenna gain for all available frequencies (and for each polarization)
* Fit a polynomal with `np.polyfit` along the frequency axis. A deg-3 polynomial seems to work well
* Use this function to interpolate/extroplate the antenna gain at any frequency

<img width="496" alt="Capture d’écran 2020-04-30 à 10 35 36" src="https://user-images.githubusercontent.com/24960512/80689983-6cb63d00-8ace-11ea-9563-64b5d8a9ce29.png">
